joskiprint/urls.py
from os import name
from django.urls import path
from . import views

app_name="joskiprint"

urlpatterns=[
    path('', views.index, name='index'),
    path('user', views.userDetails.as_view(), name='user'),
    path('order/', views.makeOrder.as_view(), name='order'),
    path('printoptions/', views.printOptions.as_view(), name='printoptions'),
    path('order/<int:pk>', views.orderSuccessful.as_view(), name='ordersuccess'),
    path('signup/', views.userCreateview.as_view(), name='usersignup'),
    path('about', views.about, name='about'),
    path('successful_orders/', views.orderSuccesses.as_view(), name='successes'),
    path('order_update/<int:pk>', views.OrderUpdate.as_view(), name='order-update'),
    path('order_delete/<int:pk>', views.OrderDelete.as_view(), name='order-delete'),
    ]

joskiservices/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import RedirectView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('joskiprint/', include('joskiprint.urls')),
    path('', RedirectView.as_view(url='joskiprint/')),

    path('accounts/', include('django.contrib.auth.urls')),

]

if settings.DEBUG:
    urlpatterns+=static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns+=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

joskiprint/models.py
from django.db import models
from django.utils import timezone
from django.db import models
# Create your models here.


# Create your models here.
class PrintOptions(models.Model):
    startPage=models.IntegerField(null=True,)
    endpage=models.IntegerField(null=True,)
    frontAndBack=models.BooleanField(null=True,)
    coloured=models.BooleanField(null=True, default=False)

    class Meta:
        ordering=['endpage']

    def __str__(self):
        return "Print Options"

class UserDetails(models.Model):
    email=models.EmailField(help_text="Email", null=True,)
    phoneNumber=models.CharField(help_text="phone number", max_length=15, null=True,)
    name=models.CharField(help_text="Name", max_length=30, null=True,)
    address=models.CharField(max_length=30, help_text="Address", null=True,)
    date_created=models.DateField(auto_now_add=True, null=True)
    class Meta:
        ordering=['name']

    def __str__(self):
        return str(self.name)

class Order(models.Model):
    file=models.FileField(null=True, help_text='select the file to upload')
    fileurl=models.CharField(null=True, help_text='url of file', blank=True, max_length=30)
    pages=models.IntegerField(null=True, help_text="how many copies")
    printOptions=models.ForeignKey(PrintOptions, null=True, on_delete=models.CASCADE, help_text="print options")
    price=models.DecimalField(help_text="price of order", decimal_places=2, max_digits=100, null=True,)
    notes=models.CharField(max_length=200, help_text="notes", null=True,)
    userDetails=models.ForeignKey(UserDetails, on_delete=models.CASCADE, null=True,)
    order_date=models.DateTimeField('order date', null=True, auto_now_add=True)
    
    class Meta:
        ordering=['-price']

    Status=(
        (0, "pending"),
        (1, 'processing'),
        (2, 'ready'),
        (3, 'delivered'),
    )
    status=models.IntegerField(null=True, choices=Status, blank=True, default=0, help_text="Order status")

    def __str__(self):
        return self.userDetails.name


class Pricing(models.Model):
    name=models.CharField(max_length=30, null=True,)
    cost=models.DecimalField(max_digits=5, decimal_places=2, help_text='cost', null=True,)
    description=models.CharField(max_length=252, null=True,)
    code=models.CharField(max_length=20, null=True,)

    class Meta:
        ordering=['name']

    def __str__(self):
        return self.name

joskiprint/forms.py
from django.db.models import fields
from django.forms import ModelForm
from .models import Order
from django.contrib.auth.models import User
from django import forms


class orderform(ModelForm):

    class Meta:
        model = Order
        fields=['file', 'fileurl', 'pages', 'notes', 'price' ]       
        

class usersignupform(ModelForm):
    class Meta:
        model=User
        fields=['email', 'username', 'password', 'first_name', 'last_name']
        widgets={'password': forms.PasswordInput()}
        





        

joskiprint/views.py
# Create your views here.
import email
from django.urls import reverse
from django.shortcuts import redirect, render
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy
from django.shortcuts import render
from django.views import generic
from .models import Order, UserDetails, PrintOptions, Pricing
from .forms import orderform, usersignupform
from django.contrib.auth.models import User
# Create your views here.
def index(request):
    return render(request, 'joskiprint/index.html')
    
def about(request):
    return render(request, 'joskiprint/about.html')

class userCreateview(CreateView):
    form_class=usersignupform
    template_name='joskiprint/usersignup.html'


    def form_valid(self, form):
        User.objects.create_user(email=self.request.POST['email'], username=self.request.POST['username'], password=self.request.POST['password'])
        return redirect('joskiprint:index')



class userDetails(CreateView):
    model=UserDetails
    fields='__all__'
    success_url=reverse_lazy('joskiprint:order')

    def get_initial(self):
        if self.request.user.is_authenticated:
            initial=super().get_initial()
            initial['email']=self.request.user.email
            initial['name']=self.request.user
            return initial
        return super().get_initial()
    
    def form_valid(self, form):
        self.request.session["username"]=self.request.POST['name']
        self.request.session['email']=self.request.POST['email']
        self.request.session['phone_no']=self.request.POST['phoneNumber']
        self.request.session['address']=self.request.POST['address']
        user_form=form.save()
        self.request.session['user_pk']=user_form.id
        return super().form_valid(form)   

    

class makeOrder(CreateView):  
    form_class=orderform
    success_url=reverse_lazy('joskiprint:printoptions')
    template_name='joskiprint/order_form.html'

    def form_valid(self, form):
        
        user=UserDetails.objects.get(
            name__exact=self.request.session["username"],
            email__exact=self.request.session["email"],
            phoneNumber__exact=self.request.session["phone_no"],
            address__exact=self.request.session["address"],
            pk=self.request.session['user_pk'],
        )
        order=form.save(commit=False)
        order.userDetails=user
        order.save()
        self.request.session['pk']= order.id
        return super().form_valid(form)
    

class printOptions(CreateView):
    model=PrintOptions
    fields='__all__'

    def form_valid(self, form):
        self.request.session['startpage']=self.request.POST['startPage']
        self.request.session['endpage']=self.request.POST['endpage']
        self.request.session['frontandback']=self.request.POST['frontAndBack']
        self.request.session['coloured']=self.request.POST['coloured']

        global order
        order=Order.objects.get(pk=self.request.session['pk'])
        order.printOptions=form.instance
        return super().form_valid(form)  
        
    def get_success_url(self):
        if self.request.user.is_authenticated:
            return reverse('joskiprint:ordersuccess', kwargs={'pk':order.pk})
        else:
            return reverse('joskiprint:index')
            
class orderSuccessful(generic.DetailView):
    model=Order
    template_name="joskiprint/ordered.html"

    def get_context_data(self, **kwargs):
        data=super().get_context_data(**kwargs)
        data['placed']='New Order Successfully placed!'
        return data
class orderSuccesses(generic.ListView):
    model=Order
    template_name="joskiprint/ordersuccess.html"   

    def get(self, *args, **kwargs):
        if not self.request.user.is_authenticated:
            return redirect('joskiprint:index')

        return super().get(*args, **kwargs)

    def get_queryset(self):
        return Order.objects.filter(userDetails__email=self.request.user.email).order_by('-order_date')

class OrderUpdate(UpdateView):
    model=Order
    fields='__all__'
    success_url=reverse_lazy('joskiprint:successes')

class OrderDelete(DeleteView):
    model=Order
    success_url=reverse_lazy('joskiprint:successes')

joskiprint/templates/joskiprint/about.html
{% extends 'joskiprint/base_generic.html' %}
{% block content %}

<div class='about'>
<h1>About us</h1>
<hr>

<p>
make order online woth joskiprint app that
takes the serivce of the printingpress to the 
next level.
</p>
</div>
{% endblock %}

joskiprint/templates/joskiprint/base_generic.html
<!DOCTYPE html>
<html lang='en'>
<head>
    {% block title %}<title>joskisprint.com</title>{% endblock %}
    <meta metacharset="utf-8">
    <meta name="viewport" contains="width=device-width", initial-scale="1">
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'joskiprint/css/styles.css' %}">
    <script src="{% static 'joskiprint/js/joski.js' %}"></script>
</head>

<body onload=" formanim(); anim();">
    
        <header class="header">
            <div id="mySidenav" class='sidebar-nav'>
                <ul>
                    <a href="javascript:void(0)" class="closebtn" onclick="closeNav()">&times;</a>
                    {% if user.is_authenticated %}   
                        <li><a href='#'>User: {{ user.get_username }}</a></li>           
                        <li><a href='{% url "joskiprint:successes"  %}'>view previous orders</a></li>
                        <li><a href="{% url 'logout' %}?next={{ request.path }}">Logout</a></li>
                    {% else %}
                        <li><a href="{% url 'login' %}?next={{ request.path }}">Login</a></li>
                        <li><a href="{% url 'joskiprint:usersignup' %}"> Signup</a></li>
                    {% endif %}
                </ul>
            </div>
                <span class='open' onclick="openNav()">&#9776;</span>

                <h1 class='welcome'>Joski's print</h1>
            
                {% block sidebar %}
                    <ul class="sidebar_nav">
                        <li><a href="{% url 'joskiprint:index' %}">Home</a></li>
                        <li><a href="">Services</a></li>
                        <li><a href="{% url 'joskiprint:about' %}">About</a></li>

                    </ul>
                {% endblock %}
        </header>

        <main class='content'>
            {% block content %}{% endblock %}
        </main>
               
        <footer><i>&copy;joskiprint services 2022.</i></footer>
        
</body>
</html>

joskiprint/templates/joskiprint/index.html
{% extends 'joskiprint/base_generic.html' %}
{% block content %}
<div class='centre_btn'>
<h1 id="service" class="service">
    <p class=service-1>welcome to joski's print website</p>
    <p class="service-2">we deal with the printingpress services</p>
</h1>
<a class='order' href='{% url "joskiprint:user" %}'>make order</a>
</div>
{% endblock %}

joskiprint/templates/joskiprint/order_confirm_delete.html
{% extends 'joskiprint/base_generic.html' %}

{% block content %}

<h1>delete Order</h1>

<form action="" method="POST">
    {% csrf_token %}
    <p class='delete'>are you sure you want to delete?</p>
    <input type="submit" value="Yes, delete.">
</form>
{% endblock %}

joskiprint/templates/joskiprint/order_form.html
{% extends 'joskiprint/base_generic.html' %}

{% block content %}
<form action="" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <table>
        {{form.as_table }}
    </table>
    <input type="submit" value="Submit">
</form>
{% endblock %}

joskiprint/templates/joskiprint/ordered.html
{% extends 'joskiprint/base_generic.html' %}
{% block content %}
    {%if placed %}
    <h1><b class='placed'>{{placed}}</b></h1>
    {%endif%}
    <ul class='details'>
        <li><image alt="{{order.file.url}}" src="{{ order.file.url }}" height="60px" width="70px"></li>
        <li>No. of pages: {{ order.pages }}</li>
        <li>Print_options: {{ order.printOptions }}</li>
        <li>Additional notes: {{ order.notes }}</li>
        <li>price: {{ order.price }}</li>
        <li>User details:{{ order.userDetails }}</li>
        <li>Dates and time of order: {{ order.order_date }}</li>
        <li>status: {{order.get_status_display}}</li>
        <li>account details: </li>
        <button style="border-radius: 5px; back♠ground-color:green;"><a style="text-decoration: none;" href="{% url 'joskiprint:order-update' order.pk %}">Update</a></button>
        <button style="border-radius: 5px; background-color:red;"><a style="text-decoration: none;" href="{% url 'joskiprint:order-delete' order.pk %}">Delete</a></button>
    </ul>
{% endblock %}

joskiprint/templates/joskiprint/ordersuccess.html
{% extends 'joskiprint/base_generic.html' %}
{% block content %}
<div class='orders'>
<h1>{{user.get_username}}'s orders</h1> 
{% if order_list %}
    <ul>
        {% for order in order_list %}  
            <hr style="color:white;">
            <a href='{% url "joskiprint:ordersuccess" order.pk %}'>
                <li class="order-suc">
                    <ul>
                        <li><image alt="{{order.file.url}}" src="{{ order.file.url }}" height="60px" width="70px"></li>
                        <li>{{ order.pages }}</li>
                        <li>{{ order.printOptions }}</li>
                        <li>{{ order.notes }}</li>
                        <li>{{ order.price }}</li>
                        <li>{{ order.userDetails }}</li>
                        <li>{{ order.order_date }}</li>
                    </ul>
                </li>
            </a>
        {% endfor %}
    </ul>
{% endif %}
<a href='{% url "joskiprint:user" %}' style="color:white;">make another order</a>
</div>

{% endblock %}

joskiprint/templates/joskiprint/printoptions_form.html
{% extends "joskiprint/base_generic.html" %}

{% block content %}
<form action="" method="POST">
    {% csrf_token %}
    <table>
        {{form.as_table}}
    </table>
    <input type="submit" value="submit">
</form>
{% endblock %}

joskiprint/templates/joskiprint/userdetails_form.html
{% extends 'joskiprint/base_generic.html' %}

{% block content %}
<form action="" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <table>
        {{form.as_table }}
    </table>
    <input type="submit" value="Submit">
</form>
{% endblock %}

joskiprint/templates/joskiprint/usersignup.html
{% extends 'joskiprint/base_generic.html' %}

{% block content %}
<form action="" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <table>
        {{form.as_table }}
    </table>
    <input type="submit" value="Submit">
</form>
{% endblock %}